version: "3"

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ./.env.production
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
   external: true
